### ISSUE TITLE
Manifest file changes after adding the plugin from cordova tool

### ISSUE THREAD

**Issue by satishk4u** [litehelpers/Cordova-sqlite-storage#100]
Hi,

After adding the SQLite plugin from  cordova command line tool, it modified my Manifest file and added one activity node as below..
 
![image](https://cloud.githubusercontent.com/assets/834947/3668189/d2cf61da-1215-11e4-956b-8543f636141b.png)
 
Can i remove this node from the manifest and what would be the impact?

Please help..

Thanks,
Satish

**Comment by jacobg** [comment]
The plugin is not activity, nor does it contain one. So why does the plugin.xml specify this activity element to be added to the manifest file? Shouldn't it be removed from plugin.xml?

**Comment by brody2consult** [comment]
Android manifest has been removed (commented out) in plugin.xml.
