### ISSUE TITLE
cannot ATTACH database within transaction (code 1)

### ISSUE THREAD

**Issue by paulness** [litehelpers/Cordova-sqlite-storage#103]
Is there any way to attach databases with this plugin?

**Comment by lasterra** [comment]
I can execute attach/detach without problems. Why project homepage said it is not possible?

"ATTACH to another database file is not supported by this version branch. Attach/detach is supported (along with the memory and iOS UNICODE \u2028 line separator / \u2029 paragraph separator fixes) in litehelpers / Cordova-sqlite-evplus-legacy-attach-detach-free (GPL or special commercial license terms)."
