### ISSUE TITLE
error parameter object in error callback is missing error code [Android]

### ISSUE THREAD

**Issue by brodybits** [litehelpers/Cordova-sqlite-storage#121]
Commit e25c6fbdbc26eac68659ce9711c9377764dbe608 by @lcsanchez includes the error code in the iOS version when an error result is to be returned for a SQL statement, in compliancy with the Web SQL (DRAFT) API. The error code is missing on the Android & WP(8) versions.

**Comment by brody2consult** [comment]
Issue with Windows platform version raised in #539. Issue with WP8 platform version moved to litehelpers/Cordova-sqlite-legacy-build-support#6.
