### ISSUE TITLE
windows8 platform support?

### ISSUE THREAD

**Issue by yupitz** [litehelpers/Cordova-sqlite-storage#129]
This plugin supports wp8 but not windows 8. It will be supported? There is another way make it run on that platform?

**Comment by ClemMakesApps** [comment]
Any update for Windows 8 support?

**Comment by brodybits** [comment]
I tried making a Windows (8) platform project from the Cordova CLI, and adding a version of the plugin from pull request #157, but for some reason I was not able to access the functionality from `window.sqlitePlugin`. Will integrate #157 once I get it working.

**Comment by brodybits** [comment]
Any pointers to help me get #157 working?

**Comment by piotrek1231** [comment]
I'm new in apache cordova and I can't understand many things. I want to use this plugin in my project and in the best scenario I want to support android, iOS and WP. Unfortunately, while testing this on Windows Phone 8.1 this plugin not working. App has the 3 places, where are local files, but database not create any file in this location. My question: Can I use this plugin on Windows Phone 8.1 and it also works on other systems ?

**Comment by brodybits** [comment]
On Mon, Dec 8, 2014 at 8:46 PM, Eion Robb <notifications@github.com> wrote:
> Sad that you didn't find my win8 plugin when you were searching
> https://github.com/EionRobb/phonegap-win8-sqlite :)
> Been happily using websql on win8 for the past couple of years with it

Hi @EionRobb, I am very interested in integrating your websql.js
script into this project (along with the SQLite3 library from
https://github.com/01org/cordova-win8, probably pre-built). The source
code of this project is available under both MIT and Apache 2.0
licenses (except for the iOS version which is MIT license only). Are
you willing to give permission to use your code in websql.js under
both MIT and Apache 2.0 licenses?

**Comment by brodybits** [comment]
https://github.com/EionRobb/phonegap-win8-sqlite is now available under both MIT and Apache 2.0 licenses and makes an excellent basis to integrate the Windows C++ library.

**Comment by brodybits** [comment]
I have now integrated and published a version for Windows (8.1) target, as documented in README.md. Unfortunately, it has a number of limitations (as documented) that I will be working on. Automatic installation using the Cordova CLI does not support all CPU targets, due to limitations in the Cordova tooling that I hope will be fixed soon.

**Comment by brody2consult** [comment]
Version for Windows 8/8.1 is now released, closing.
