### ISSUE TITLE
Triggers (maybe) broken on Android; needs testing/investigation on iOS & WP(8)

### ISSUE THREAD

**Issue by brodybits** [litehelpers/Cordova-sqlite-storage#133]
I raised this issue in response to the following inquiry by Jordi Solsona on the Cordova-SQLitePlugin forum:

From:  <***>
Date: Tue, Sep 9, 2014 at 8:58 PM
Subject: [Cordova-SQLitePlugin] Triggers not working in Android 4.4.4
To: Cordova-SQLitePlugin@googlegroups.com

Hello,

My database have triggers after inserts and updates.
I can create the tables and triggers correctly (success event is raised)

When in my code I make inserts/updates, triggers are not executed, but the insert query returns a success event.

rowsAffected inside then application after an insert is 1.
rowsAffected in a Sqlite Client after an insert is > 1. (because trigger executers more sentences)

Are triggers supported by the plugin? There is any limitation to use them?
 
Thank you.

**Comment by ModusPwnens1337** [comment]
Is there any movement on this? Are the triggers truly broken on Android?

**Comment by brody2consult** [comment]
The following test shows the issue with a TRIGGER on Android when the `androidDatabaseImplementation: 2` setting is used:

``` js

        it(suiteName + 'INSERT with TRIGGER', function(done) {
          var db = openDatabase('INSERT-with-TRIGGER-test.db', '1.0', 'Test', DEFAULT_SIZE);

          db.transaction(function(tx) {
            tx.executeSql('DROP TABLE IF EXISTS tt1;');
            tx.executeSql('DROP TABLE IF EXISTS tt2;');

            tx.executeSql('CREATE TABLE tt1 (data);');
            tx.executeSql('CREATE TABLE tt2 (data);');

            tx.executeSql("CREATE TRIGGER t1 AFTER INSERT ON tt1 BEGIN INSERT INTO tt2 VALUES(datetime('now')); END;");

            tx.executeSql('INSERT INTO tt1 VALUES (?)', ['test-value'], function(ignored1, rs1) {
              // EXPECTED: CORRECT RESULT:
              expect(rs1).toBeDefined();
              expect(rs1.insertId).toBeDefined();
              expect(rs1.rowsAffected).toBeDefined();
              expect(rs1.rowsAffected).toBe(2);

              tx.executeSql('SELECT count(*) AS cnt FROM tt2', [], function(ignored, resultSet) {
                // EXPECTED: CORRECT RESULT:
                expect(resultSet).toBeDefined();
                expect(resultSet.rows).toBeDefined();
                expect(resultSet.rows.length).toBe(1);
                expect(resultSet.rows.item(0).cnt).toBeDefined();
                expect(resultSet.rows.item(0).cnt).toBe(1);

                // Close (plugin only - always the case in this test) & finish:
                (isWebSql) ? done() : db.close(done, done);
              });
            });
          }, function(e) {
            // ERROR RESULT (NOT EXPECTED):
            expect(false).toBe(true);
            expect(e).toBeDefined();

            // Close (plugin only) & finish:
            (isWebSql) ? done() : db.close(done, done);
          });
        }, MYTIMEOUT);
```

When the `androidDatabaseImplementation: 2` setting is used the rowsAffected is incorrect. This is already documented but will be clarified.
