### ISSUE TITLE
Multiple rowsAffected for INSERT (Android)

### ISSUE THREAD

**Issue by brodybits** [litehelpers/Cordova-sqlite-storage#136]
The Android version assumes only one row is affected upon successful INSERT statement but this is not always the case. For example, the following INSERT statement from http://stackoverflow.com/questions/4253804/insert-new-column-into-table-in-sqlite is possible:

    INSERT INTO {tableName} (name, qty, rate) SELECT name, qty, rate FROM TempOldTable;

A possible solution is given here: http://stackoverflow.com/questions/6659673/get-updated-rows-count-from-sqlite-in-android-using-a-raw-query

This may also be needed to deal with triggers (#133)

In addition, this may be a better solution to get the rowsAffected for UPDATE/DELETE pre-Honeycomb.

**Comment by brody2consult** [comment]
NOTE: Yes we should consider dropping support for pre-Honeycomb devices, assuming this is also OK for the Amazon reader version (which some people _do_ use) but that is a side point. This is an issue on _all_ versions of the Android sqlite database API.

The Android version uses the the [sqlite4java](https://code.google.com/p/sqlite4java/) library by default, which solves this problem. Only if the database is opened with `androidDatabaseImplementation: 2` is the Android version affected by this issue. Note that the Amazon reader version is still affected by this issue.

The solution following http://stackoverflow.com/questions/6659673/get-updated-rows-count-from-sqlite-in-android-using-a-raw-query is to internally execute a query such as "SELECT changes() as mychanges" to get the number of rows affected. The iOS version gets the total number of changes before and after each query and reports the difference in `rowsAffected`, and I would like to do this when using the Android database API as well (using an internal query such as "SELECT total_changes() as mytotal").

In addition, if we also use an internal query like "SELECT last_insert_rowid() as insertid" to get the `insertId`, then all user sql queries can be executed using `SQLiteDatabase.rawQuery()`. (BEGIN/COMMIT/ROLLBACK requests from the Javascript would still have to be handled using `SQLiteDatabase.beginTransaction()`/`SQLiteDatabase.setTransactionSuccessful()`/`SQLiteDatabase.endTransaction()`.)

_UPDATE August 2016: This is no longer an issue when using the default Android database implementation. This is still an issue when using the built-in Android database implementation (when using the `androidDatabaseImplementation: 2` setting. This is documented and will probably not be fixed._
