### ISSUE TITLE
Database fails to load when Cordova app restarts.

### ISSUE THREAD

**Issue by JonathanAquino** [litehelpers/Cordova-sqlite-storage#141]
If a Cordova app is terminated (due to low memory conditions - [example](https://discussions.apple.com/thread/5380124?tstart=0)), when it restarts, the database fails to load - if you do a transaction and executeSql, the callback is never called.

This is a serious problem, since it is common for apps to be terminated.

I think this is related to the plugin [not yet supporting multi-page apps](https://discussions.apple.com/thread/5380124?tstart=0).

This issue is with single-page apps, but it probably has the same root cause.

**Comment by brody2consult** [comment]
This looks like an issue with window.location changes and window.location.reload() and will be handled in #486. Please see #486 for further discussions.

**Comment by Textras** [comment]
@brodybits was this ever fixed, or is there a known work around apart from avoiding `window.location` and the related methods? I occasionally get the same problem, on the latest version of the plugin. It reaches the transaction, but neither reaches the result of the query nor the error callback.

**Comment by CodeWithOz** [comment]
@brodybits was this ever fixed, or is there a known workaround apart from avoiding `window.location` and its related methods? I occasionally see the same problem as OP and I'm using the latest version of the plugin. It reaches the transaction, but hangs without ever reaching the success or error callbacks of the query.
