### ISSUE TITLE
Use Cordova with FTS3

### ISSUE THREAD

**Issue by calebeaires** [litehelpers/Cordova-sqlite-storage#156]
How to use search functionality based on SQLite and FTS3 with this plugin

**Comment by brodybits** [comment]
Not sure if the sqlite implementation has FTS3/4/etc. integrated, and for which platforms, if so. A test case would be ideal (not too big). For future consideration.

**Comment by Dahkon** [comment]
Hello,
I can't make it work.
I use this plugin to open database and populate it with a .sql file. It works fine with regular queries.

When I try to implement FTS3 following [sqlite documentation](http://www.sqlite.org/fts3.html#section_1_2) :
> CREATE VIRTUAL TABLE data USING fts3();

I got no errors but regular INSERT or SELECT doesn't work anymore.

I didn't try MATCH queries yet.

**Comment by calebeaires** [comment]
It is working now.
