### ISSUE TITLE
Phonegap android issue

### ISSUE THREAD

**Issue by ljammala** [litehelpers/Cordova-sqlite-storage#164]
I have added Sqlite plugin to my Phonegap project and it works perfectly fine in iOS. With Android, I see the following error:
The database tables are created fine.
 Can you please help?

12-05 22:57:55.926: E/SQLitePlugin(21959): unexpected error
12-05 22:57:55.926: E/SQLitePlugin(21959): org.json.JSONException: Value 15398 at params of type java.lang.Integer cannot be converted to JSONArray
12-05 22:57:55.926: E/SQLitePlugin(21959): 	at org.json.JSON.typeMismatch(JSON.java:100)
12-05 22:57:55.926: E/SQLitePlugin(21959): 	at org.json.JSONObject.getJSONArray(JSONObject.java:548)
12-05 22:57:55.926: E/SQLitePlugin(21959): 	at org.pgsqlite.SQLitePlugin.executeAndPossiblyThrow(SQLitePlugin.java:146)
12-05 22:57:55.926: E/SQLitePlugin(21959): 	at org.pgsqlite.SQLitePlugin.execute(SQLitePlugin.java:82)
12-05 22:57:55.926: E/SQLitePlugin(21959): 	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:65)
12-05 22:57:55.926: E/SQLitePlugin(21959): 	at org.apache.cordova.PluginManager.execHelper(PluginManager.java:242)
12-05 22:57:55.926: E/SQLitePlugin(21959): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:227)
12-05 22:57:55.926: E/SQLitePlugin(21959): 	at org.apache.cordova.ExposedJsApi.exec(ExposedJsApi.java:53)
12-05 22:57:55.926: E/SQLitePlugin(21959): 	at org.apache.cordova.CordovaChromeClient.onJsPrompt(CordovaChromeClient.java:229)
12-05 22:57:55.926: E/SQLitePlugin(21959): 	at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:882)
12-05 22:57:55.926: E/SQLitePlugin(21959): 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-05 22:57:55.926: E/SQLitePlugin(21959): 	at android.os.Looper.loop(Looper.java:137)
12-05 22:57:55.926: E/SQLitePlugin(21959): 	at android.app.ActivityThread.main(ActivityThread.java:4950)
12-05 22:57:55.926: E/SQLitePlugin(21959): 	at java.lang.reflect.Method.invokeNative(Native Method)
12-05 22:57:55.926: E/SQLitePlugin(21959): 	at java.lang.reflect.Method.invoke(Method.java:511)
12-05 22:57:55.926: E/SQLitePlugin(21959): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1004)
12-05 22:57:55.926: E/SQLitePlugin(21959): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:771)
12-05 22:57:55.926: E/SQLitePlugin(21959): 	at dalvik.system.NativeStart.main(Native Method)
12-05 22:57:55.926: W/PluginManager(21959): THREAD WARNING: exec() call to SQLitePlugin.backgroundExecuteSqlBatch blocked the main thread for 4552ms. Plugin should use CordovaInterface.getThreadPool().

**Comment by brody2consult** [comment]
Unfortunately this is not enough information to reproduce a problem, closing. If you still see a problem, please post a complete, self-contained test program that can demonstrate the issue thanks.
