### ISSUE TITLE
SQLLIteplugin.open error

### ISSUE THREAD

**Issue by gingy24** [litehelpers/Cordova-sqlite-storage#171]
Hello,
I am trying to use SQLLItePlugin for Android but its not working. I will list my steps:
1. I have installed cordova pjhonegap from http://phonegap.com. I am developing my mobile app Phonegap, html5, javascript, css3 using Netbeans as IDE.
2. Downloaded plugin from https://github.com/brodysoft/Cordova-SQLitePlugin.
3. Added SQLitePlugin.js to js folder of project.
4. Added com.brodysoft.sqlitePlugin.file=https://github.com/brodysoft/Cordova-SQLitePlugin.git in plugin.properties.
5. Am opening database on deviceready as
 onDeviceReady: function () {
app.receivedEvent('deviceready');
       var app = {
   initialize: function () {
        this.bindEvents();
    },
    bindEvents: function () {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
    onDeviceReady: function () {
        app.receivedEvent('deviceready');
        var db = window.sqlitePlugin.openDatabase('gdata.db');
        console.log('ready');
        
        
         db.transaction(function (tx) {
	            tx.executeSql('DROP TABLE IF EXISTS test_table');
	            tx.executeSql('CREATE TABLE IF NOT EXISTS test_table (id integer primary key, data text, data_num integer)');
	
	            // demonstrate PRAGMA:
	            db.executeSql("pragma table_info (test_table);", [], function (res) {
	                console.log("PRAGMA res: " + JSON.stringify(res));
	            });
	
	            tx.executeSql("INSERT INTO test_table (data, data_num) VALUES (?,?)", ["test", 100], function (tx, res) {
	                console.log("insertId: " + res.insertId + " -- probably 1");
	                console.log("rowsAffected: " + res.rowsAffected + " -- should be 1");
	
	                db.transaction(function (tx) {
	                    tx.executeSql("select count(id) as cnt from test_table;", [], function (tx, res) {
	                        console.log("res.rows.length: " + res.rows.length + " -- should be 1");
	                        console.log("res.rows.item(0).cnt: " + res.rows.item(0).cnt + " -- should be 1");
	                    });
	                });
	
	            }, function (e) {
	                console.log("ERROR: " + e.message);
	            });
        });
        
        

    },
    // Update DOM on a Received Event
    receivedEvent: function (id) {
        var parentElement = document.getElementById(id);
        console.log('Received Event: ' + id);
    }
};
app.initialize();
6. Running the build on android devvice directly.

It keeps on throwing the error
Uncaught TypeError: Object #<Object> has no method 'exec' (13:52:13:450 | error, javascript)
    at SQLitePlugin.open (www/js/libs/SQLitePlugin.js:112:15)
    at SQLitePlugin (www/js/libs/SQLitePlugin.js:54:10)
    at (anonymous function) (www/js/libs/SQLitePlugin.js:425:14)
    at (anonymous function) (www/js/libs/SQLitePlugin.js:30:20)
    at createandpopulatedb (www/js/dborarray.js:30:30)
    at onDeviceReady3 (www/dborarray.html:96:33)
    at onload (www/dborarray.html:16:155)
SQLitePlugin openargs: {"name":"gdata.db"} (13:52:19:609)
  at www/js/libs/SQLitePlugin.js:39
  
  Can somebody help.

**Comment by nolanlawson** [comment]
It sounds like you haven't correctly installed Cordova/PhoneGap or the plugin. Check the developer tools to see if those two javascript files (`cordova.js`, `sqlite-plugin.js`) are being loaded.

**Comment by nolanlawson** [comment]
Also are you waiting for the `deviceready` event?

**Comment by gingy24** [comment]
Thanks for replying.

Both these files are getting loaded, I can see in the log. Infact when i debug, it says error is coming in sqlliteplugin.js. I had pasted the error being thrown.

**Comment by nolanlawson** [comment]
Try using `window.openDatabase` instead of `window.sqlitePlugin.openDatabase` (i.e. the built-in WebSQL instead of SQLite plugin). If your code succeeds, then it's a bug in the SQLite plugin.

Also it would be helpful to know the Android version, device, PhoneGap version, plugin version, etc. :)

**Comment by gingy24** [comment]
Window.opendatabase works just perfectly fine. I was trying to use SQLLite so that i can use a prepopulated database and size benefit.

I am opening the sqllite db after deviceready. Will test it once more, and give you all logs and versions.

Thanks.

**Comment by gingy24** [comment]
Hey Nolan,
PFA the files. Let me know if you want anything else.
Today the behaviour was even more erratic. I ran this code with about 10 or more different database names, and code worked only twice. Rest all tiimes, either it didnt do anything or gave me following error
creating dbobj started (12:10:34:041)  at www/js/index.js:50SQLitePlugin openargs: {"name":"gingy3.db"} (12:10:34:051)  at www/js/SQLitePlugin.js:39undefined (12:10:34:060)  at www/js/SQLitePlugin.js:52> 
One thing to notice was, whenever the database got created, it was with alert('deviceready'); code inserted in index.js.
My android version is 4.4.2.Phonegap cordova and Plugin has been downloaded just yesterday so must be latestt. Both from offical links.
Am I doing something wrong? Also if database is created, where can I see it in my device?
ThanksAnupam


 

     On Tuesday, 6 January 2015 10:26 PM, Anupam <anupamspeaks@yahoo.com> wrote:
   

 Window.opendatabase works just perfectly fine. I was trying to use SQLLite so that i can use a prepopulated database and size benefit.
I am opening the sqllite db after deviceready. Will test it once more, and give you all logs and versions.
Thanks.

On 06-Jan-2015, at 9:59 pm, Nolan Lawson <notifications@github.com> wrote:


Try using window.openDatabase instead of window.sqlitePlugin.openDatabase (i.e. the built-in WebSQL instead of SQLite plugin). If your code succeeds, then it's a bug in the SQLite plugin.Also it would be helpful to know the Android version, device, PhoneGap version, plugin version, etc. :)—

**Comment by brodybits** [comment]
Something went wrong with your installation. Reading your description, it looks like you installing the plugin manually instead of using the cordova CLI, which has not been officially supported since Cordova 3.0. Cordova also needs to know about the plugin, which you do in config.xml (res/xml/config.xml) in the features section.

I wish you good luck since this is not officially supported by Cordova. I *may* document this in the readme if it will help enough people.
