### ISSUE TITLE
SQLite + Pouch causes silent replication failure

### ISSUE THREAD

**Issue by jfspencer** [litehelpers/Cordova-sqlite-storage#186]
When using the sqlite plugin with pouchDB, replication always fails to complete on iOS devices. There is an open issue with pouch here 
https://github.com/pouchdb/pouchdb/issues/3548

They suspect that the cause may be more sqlite than pouch. The main thought there is pouch replicates normally using standard websql.

I have assembled a demo application here - https://drive.google.com/file/d/0B0-I41uSyatNM0xPQ192OXhHeDA/view

It is an ionic application that is completely configured with the latest sqlite plugin and latest pouch versions. Within a setup ionic environment (for details see http://ionicframework.com/getting-started/)

run
 
    ionic build ios
    ionic emulate/run ios.

Then type in the test couchdb address below to begin replication. or use any other couch server you want.

Test replication database here - https://testreplication.iriscouch.com/test/ it contains about 5000 documents. typically replication will not get past 800 or so.

Also configuring the batch size and limit options affects the number of requests that occur. low size/limits yield more requests and fewer documents, and the reverse is true. replicating a single document per request yields about 66 requests before stopping. 200 docs per request stops at around 14.

Let me know how I can help. Thanks!

**Comment by nolanlawson** [comment]
@jfspencer If you have any experience with iOS, you could take a look at [SQLitePlugin.m](https://github.com/brodysoft/Cordova-SQLitePlugin/blob/31dca3005a72132faa23f1fa2cb43f63e9bbe818/src/ios/SQLitePlugin.m). :smiley:

**Comment by brodybits** [comment]
I wonder if #190 is related? I will look at it later.

**Comment by jfspencer** [comment]
It does sound very related. The only variation with #190 is that reducing
batch size to one doc per request only completes about 60 fetch loops
before failing. I wonder if there is another factor involved other than a
document transaction.

On Monday, February 23, 2015, Chris Brody <notifications@github.com> wrote:

> I wonder if #190
> <https://github.com/brodysoft/Cordova-SQLitePlugin/issues/190> is
> related? I will look at it later.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brodysoft/Cordova-SQLitePlugin/issues/186#issuecomment-75598421>
> .
>


-- 

Cheers,


James

**Comment by n8sabes** [comment]
I have been chasing this issue for a few days and appears to be resulting from 500-1000 transactions over the lifecycle of the application on iOS. I believe it occurs on SQLite and WebSQL.

Please see the following:

Simple Example
https://github.com/n8sabes/ionic-sqlite-1000-transactions-ios-bug

#190 as pointed out by brodybits
https://github.com/brodysoft/Cordova-SQLitePlugin/issues/190

#33 on davibe/Phonegap-SQLitePlugin
https://github.com/davibe/Phonegap-SQLitePlugin/issues/33

**Comment by jfspencer** [comment]
I have been able to transact multiple thousands of docs using webSQL +
PouchDB. If you remove the SQLite plugin from my example app above and
rebuild, it will replicate all 5000+ docs to the app using the supplied
replication address.

One side note, in index.html as the app is replicating it produces many
iframe elements with a src="gap://ready" is that normal for Cordova/phone
gap apps?

On Monday, February 23, 2015, n8sabes <notifications@github.com> wrote:

> I have been chasing this issue for a few days and appears to be resulting
> from 500-1000 transactions over the lifecycle of the application on iOS. I
> believe it occurs on SQLite and WebSQL.
>
> Please see the following:
>
> Simple Example
> https://github.com/n8sabes/ionic-sqlite-1000-transactions-ios-bug
>
> #190 <https://github.com/brodysoft/Cordova-SQLitePlugin/issues/190> as
> pointed out by brodybits
> #190 <https://github.com/brodysoft/Cordova-SQLitePlugin/issues/190>
>
> #33 <https://github.com/brodysoft/Cordova-SQLitePlugin/issues/33> on
> davibe/Phonegap-SQLitePlugin
> davibe/Phonegap-SQLitePlugin#33
> <https://github.com/davibe/Phonegap-SQLitePlugin/issues/33>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brodysoft/Cordova-SQLitePlugin/issues/186#issuecomment-75600770>
> .
>


-- 

Cheers,


James
