### ISSUE TITLE
wp8 converts to negative too big integers

### ISSUE THREAD

**Issue by jlegido** [litehelpers/Cordova-sqlite-storage#195]
Issue
When I do a select of a too big integer value, wp8 converts it to a negative value, in this example "-1754182378_"

Sqlite table
CREATE TABLE INFO(last_sync_date INTEGER);
INSERT INTO "INFO" VALUES(1424174959894);

Software versions:
Cordova -> 3.6.3-0.2.13
wp8 -> Windows Phone 8.1 update
Sqlite plugin -> 1.0.4

Snippet of code:
```
// Gets Unix timestamp (in miliseconds) of last DB update in remote server
Location.prototype.getLastSyncDate = function(querySuccess, queryError) {
    this.db.transaction(queryDB, queryError, this.successDB("getLastSyncDate"));

    function queryDB(tx) {
        var sqlQuery = 'select * from INFO';
        tx.executeSql(sqlQuery, [], querySuccess, this.errorDB);
    }
}

Additional info
-Same code with same plugin works ok in Android and IOS
-If I trim the number to 9 digits (instead of 13) it works as expected. I didn't tried to find the maximum supported number.

PD: many thanks for your great work

**Comment by brodybits** [comment]
Thanks for reporting this!

**Comment by martatw** [comment]
Hi,

I have the same Issue, Do you know some workariund to fix it? When It will be fixed?

**Comment by jlegido** [comment]
Hi there.

At the moment I have no solution, I just convert the numbers at app level.

Cheers.

Javier

**Comment by martatw** [comment]
Hi,

After deeper investigation, I have found out that plugin correnctly is adding int64 to DB. However the bug occured after getting data from BD. There is a code in wp\SQLite.cs : line: 1958; function ExecuteDeferredQuery():

```
                    switch (colType)
                    {
                        case SQLite3.ColType.Text:
                            targetType = typeof(string);
                            break;
                        case SQLite3.ColType.Integer:
                            targetType = typeof(int);
                            break;
                        case SQLite3.ColType.Float:
                            targetType = typeof(double);
                            break;
                        default:
                            targetType = typeof(object);
                            break;
                    }
```

Each Integer data is converted to int32. After changing to Int64 it works fine. Do You think that this change might have some negative inpact?

(I am speaking about windows Phone 8.1 app)

BR
Marta

**Comment by brody2consult** [comment]
> There is a code in wp\SQLite.cs : line: 1958; function ExecuteDeferredQuery():
> 
> ```
>                 switch (colType)
>                 {
>                     case SQLite3.ColType.Text:
>                         targetType = typeof(string);
>                         break;
>                     case SQLite3.ColType.Integer:
>                         targetType = typeof(int);
>                         break;
>                     case SQLite3.ColType.Float:
>                         targetType = typeof(double);
>                         break;
>                     default:
>                         targetType = typeof(object);
>                         break;
>                 }
> ```
> 
> Each Integer data is converted to int32. After changing to Int64 it works fine.

Thanks @martatw!

A pull request for this would be really helpful (I cannot try this change until I return from vacation in January).

**Comment by brody2consult** [comment]
When I tried `typeof(long)` and `typeof(Int64)` it would return number values as strings. The following change does the trick:

``` diff
diff --git a/src/wp/SQLite.cs b/src/wp/SQLite.cs
index f1b96c2..268d569 100644
--- a/src/wp/SQLite.cs
+++ b/src/wp/SQLite.cs
@@ -1958,8 +1958,6 @@ namespace SQLite
                                 targetType = typeof(string);
                                 break;
                             case SQLite3.ColType.Integer:
-                                targetType = typeof(int);
-                                break;
                             case SQLite3.ColType.Float:
                                 targetType = typeof(double);
                                 break;
```
