### ISSUE TITLE
Compile error: CDVPlugin class SQLitePlugin does not exist

### ISSUE THREAD

**Issue by arash01** [litehelpers/Cordova-sqlite-storage#205]
Hi,
I am getting error below while running my app in ios.

CDVPlugin class SQLitePlugin (pluginName: SQLitePlugin) does not exist
ERROR: Plugin 'SQLitePlugin' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.

All other plugins are working fine.
Thanks.

**Comment by brodybits** [comment]
Not enough information. Please specify how you installed the plugin, such as manual installation, using the `plugman` tool, or using the `cordova` CLI.

Note that manual installation is NOT supported for Cordova 3.0(+).
