### ISSUE TITLE
Closing one of multiple db objects for the same db file causes failure

### ISSUE THREAD

**Issue by brodybits** [litehelpers/Cordova-sqlite-storage#209]
While it is possible to support db connection objects to the same db file, closing one of the db connection objects ~~quietly~~ breaks the other db connection.

**UPDATED REPRODUCTION SCENARIO:** The following reproduction scenario fails ~~with a timeout~~:

```Javascript
        if (!isWebSql) test(suiteName + ' close one of multiple db handle', function () {
          var dbname = 'multi-handle-db-close-one.db';
          var dbw = openDatabase(dbname, "1.0", "Demo", DEFAULT_SIZE);
          var dbr = openDatabase(dbname, "1.0", "Demo", DEFAULT_SIZE);

          stop(1);

          dbw.transaction(function (tx) {
            tx.executeSql('DROP TABLE IF EXISTS tt');
            tx.executeSql('CREATE TABLE IF NOT EXISTS tt (test_data)');
            tx.executeSql('INSERT INTO tt VALUES (?)', ['My-test-data']);
          }, function(error) {
            console.log("ERROR: " + error.message);
            ok(false, error.message);
            start(1);
          }, function() {
            dbw.close(function () {
              dbr.readTransaction(function (tx) {
                tx.executeSql('SELECT test_data from tt', [], function (tx, result) {
                  equal(result.rows.item(0).test_data, 'My-test-data', 'read data from reader handle');
                  start(1);
                });
              }, function(error) {
                console.log("ERROR: " + error.message);
                ok(false, error.message);
                start(1);
              });
            }, function (error) {
              ok(false, 'close error callback not to be called after database is closed');
              start(1);
            });
          });
        });
```

This issue was discovered by consideration of some CoffeeScript/Javascript restructuring and possible redesign to support solution to #184.

**Comment by brodybits** [comment]
**IMPORTANT NOTE** (implementation): if a db handle object has been closed, it should abort all attempts to execute SQL statements and transactions, and should reject any future attempt to close with an error callback.

**Comment by brody2consult** [comment]
Fixed in documentation: using the `close` method will close the database on the native side and invalidate all handles on the JavaScript side. For reference: https://www.infoq.com/articles/0-bugs-policy

A FUTURE TODO is to add a `dispose` method that will simply invalidate a single database handle object. The database would be closed on the native side once all handles on the JavaScript side are invalidated.
