### ISSUE TITLE
Plugin is not working on ios8

### ISSUE THREAD

**Issue by jsundn** [litehelpers/Cordova-sqlite-storage#214]
Hi!

The plugin will not work for me on ios 8, but works fine on lesser versions. When I'am trying to write to the database nothing happens other than the error callback is called with an error object (and error property is undefined).

Cannot give so much more info :/

Does somebody knows something more about this problem?

**Comment by brodybits** [comment]
Did you try the test suite?

**Comment by jsundn** [comment]
Yeah, but it the tests just passes. No fails..

**Comment by brodybits** [comment]
I need your help to investigate this issue further. Please try to isolate what is not working with iOS 8.

**Comment by safilsunny** [comment]
We also have the same issue with iOS 8. The same code works perfectly in Android.

**Comment by brodybits** [comment]
On Mar 27, 2015 7:33 AM, "Safil Sunny" <notifications@github.com> wrote:
>
> We also have the same issue with iOS 8. The same code works perfectly in
Android.

Did you try the test suite under test-www/www?

**Comment by brody2consult** [comment]
The iOS version has been corrected to override pluginInitialize, and new sqlite3 source is now embedded in the build. Please report if it still does not work with iOS 8.
