### ISSUE TITLE
Uncaught TypeError: Cannot read property 'openDatabase' of undefined

### ISSUE THREAD

**Issue by MohamedMehrez** [litehelpers/Cordova-sqlite-storage#225]
After few days of trying to figure out how this plugin works,all i get is errors,i re-started a whole new project from scratch using ionic,i've seen a lot of good feedback on this article and i did follow its steps. https://blog.nraboy.com/2014/11/use-sqlite-instead-local-storage-ionic-framework/
Now i get this error :
Uncaught TypeError: Cannot read property 'openDatabase' of undefined    ng-cordova.js:10
BTW i'm using ripple on chrome to emulate.
Does anybody know how to fix this ?
Thanks.

**Comment by brody2consult** [comment]
Unfortunately this is not enough information. Also when you add the plugin please use the new location.

**Comment by Amenocy** [comment]
i use your sample code 
    var db = window.sqlitePlugin.openDatabase("Db.db", "1.0", "Demo", -1);
and get error 
D/CordovaLog(20458): file:///android_asset/www/index.html: Line 27 : Uncaught TypeError: Cannot call method 'openDatabase' of undefined

E/Web Console(20458): Uncaught TypeError: Cannot call method 'openDatabase' of undefined at file:///android_asset/www/index.html:27

**Comment by brody2consult** [comment]
On Fri, Apr 10, 2015 at 9:56 PM, Amenocy notifications@github.com wrote:

> i use your sample code
> var db = window.sqlitePlugin.openDatabase("Db.db", "1.0", "Demo", -1);
> and get error
> D/CordovaLog(20458): file:///android_asset/www/index.html: Line 27 : Uncaught TypeError: Cannot call method 'openDatabase' of undefined
> 
> E/Web Console(20458): Uncaught TypeError: Cannot call method 'openDatabase' of undefined at file:///android_asset/www/index.html:27

That means that for some reason, `SQLitePlugin.js` is not actually loaded before your code is run. Please make sure you wait for the `deviceready` event.

**Comment by Amenocy** [comment]
hum .now i got this error 
D/CordovaLog(22823): file:///android_asset/www/index.html: Line 25 : Uncaught Error: SECURITY_ERR: DOM Exception 18
line 25:   var db = window.openDatabase("Db.db", "1.0", "Demo", -1);
code in 
 var module = angular.module('app', ['onsen']).
  run(function() {

**Comment by Amenocy** [comment]
change  line 25: var db = window.openDatabase("Db.db", "1.0", "Demo", -1);
to 
 line 25: var db = window.openDatabase("Db.db", "1.0", "Demo", 1);
solve problem

**Comment by nolanlawson** [comment]
If you're using `window.openDatabase`, then you are using the built-in WebSQL database and not the SQLite Plugin (`window.sqlitePlugin.openDatabase`).

**Comment by jlem** [comment]
I'm having this same issue. Here's what I'm doing:
1. Using ionic + angular
2. Installed plugin via `cordova plugin add cordova-sqlite-storage`
3. Attempted the following in my main app.js file:

``` javascript
app.run(function($ionicPlatform){
    $ionicPlatform.ready(function(){
            var db = window.sqlitePlugin.openDatabase({name: "my.db", location: 2, createFromLocation: 1});
    });
});
```
1. run `ionic serve` to view it in Chrome on my OSX desktop. Does this even work in desktop chrome, or does it _have_ to run in an iOS emulator or Android emulator?

If it can work in Chrome, what am I doing wrong? Does `$ionicPlatform.ready()` not account for device ready?

**Comment by brody2consult** [comment]
@jlem, unfortunately the `browser` target is not supported by this project, for future consideration (see #297). You might want to check out https://github.com/samikrc/CordovaSQLite (with its own custom API).

For others: this issue was raised almost 6 months ago with not enough information. This issue is now closed and locked.

If you continue to see issues with using this plugin, please follow the procedure in https://github.com/litehelpers/Cordova-sqlite-storage#support.

In case of questions, you may ask at: https://github.com/litehelpers/Cordova-sqlite-help/issues.
