### ISSUE TITLE
Calling Drop Table does not delete it

### ISSUE THREAD

**Issue by joaopgrassi** [litehelpers/Cordova-sqlite-storage#39]
I had a table with two columns. Due to changes on the table structure, I had to add 3 more columns and change the name of the previous two. I found easier to drop the table and than recreat it. What is weird is I tried to select a new column for the recreated table, and it keeps saying column does not exist. So I did a select * to se which columns are being returned. Turned out that the new table wasn't created and the old one is still there. Any help appreciated.

**Comment by brody2consult** [comment]
Added to README.md
