### ISSUE TITLE
Pragma foreign_keys ON doesn't work on IOS

### ISSUE THREAD

**Issue by gogiel** [litehelpers/Cordova-sqlite-storage#45]
Problem:
I am unable to set PRAGMA foreign_keys to ON on iOS 7 (Iphone Simulator).
Code example:
~~~
db.transaction(function(tx){
    tx.executeSql("PRAGMA foreign_keys=ON;", [], function(tx, res){
        tx.executeSql("PRAGMA foreign_keys;", [], function(tx, res){
            console.log('foreign_keys:', res.rows.item(0).foreign_keys); // foreign_key: 0
        })
    })
}, function(e){
    console.log(e)
});
~~~

**Comment by ronaldaraujo** [comment]
Any solution? I'm having the same problem!

**Comment by KPaul31** [comment]
Sorry for repeating but has anyone found a solution for this "bug".

**Comment by ronaldaraujo** [comment]
KPaul31 tried running the code that you mentioned, but it did not work...

**Comment by mirko77** [comment]
As I posted above, one solution is to use triggers and forget about PRAGMA on iOS

**Comment by ronaldaraujo** [comment]
Hi mirko77. I am new to developing for android. Could you show an example. Thanks.

**Comment by mirko77** [comment]
The problem with PRAGMA is on iOS only, on Android it works ace.

This is how you activate it , as it is off by default

    EC.db = window.sqlitePlugin.openDatabase({
                name : "database"
            });

    //enable PRAGMA to use foreign keys constraint: it is OFF by default
    EC.db.executePragmaStatement("PRAGMA foreign_keys=ON;", function(res) {
         console.log("PRAGMA res: " + JSON.stringify(res));
    });

`EC.db` is your database object

**Comment by ronaldaraujo** [comment]
Taking advantage of the space, someone could tell me where the .db file generated by the plugin? I am planning to run some queries via shell coommand using sqlit3 ...

**Comment by mirko77** [comment]
on Android is on `/data/data/<package_name>/databases/`

you need root access on the device to access that folder

**Comment by mirko77** [comment]
`executePragmaStatement` does not work anymore with the latest release?

It used to, but now I get a `"Object [object Object] has no method 'executePragmaStatement'"`

**Comment by brody2consult** [comment]
To execute a PRAGMA statement, please use `db.executeSql()` _as documented in README.md_.

I will add a note to README.md to make this more clear.

**Comment by brody2consult** [comment]
Note added to README.md to make this clear.
