### ISSUE TITLE
connect to local DB file in desktop during design

### ISSUE THREAD

**Issue by meisam3322** [litehelpers/Cordova-sqlite-storage#493]
I am working on a Cordova project. i need to use DB , but i don't know in which folder of my project have to place my DB file for android in my PC

**Comment by brodybits** [comment]
In general you cannot access the database directory on an Android app without rooting the device. Your app should be able to start with a blank database, populate whatever data it has to store, and retrieve the data whenever necessary.

The cordova-sqlite-ext version supports pre-populated databases. Please follow the documentation in cordova-sqlite-ext if you want to use this feature.
