### ISSUE TITLE
Parameterized IN statement

### ISSUE THREAD

**Issue by paulness** [litehelpers/Cordova-sqlite-storage#98]
Parameterized IN statement

Is this even possible using this plugin?

**Comment by CroModder** [comment]
Came here to find a solution for this and ended up using @nolanlawson snippet with one correction.
In my case, it didn't work when I passed the array directly like that. I needed to use spread on it:
`executeSql(query, [...tags])`
And if you are using ES2015 you can use the shorter version for generating placeholders:
`let query = 'SELECT foo FROM bar WHERE foo.id IN (' + arr.map(() => '?').join(',') + ')';`
